### ISSUE TITLE
Order independent hash

### ISSUE THREAD

**Issue by qnzhou** [abseil/abseil-cpp#1061]
Given a fixed-size container, say `std::array<T, 3>`, I am wondering if it is possible to create a hash with `HashState::combine(...)` that is independent of the ordering of the data without sorting?

For example, with `std::hash`, I can do the following (despite it being a horrible hash function):
```c++
size_t hash(const std::array<int, 3>& data) {
    std::hash<int> h;
    return h(data[0]) ^ h(data[1]) ^ h(data[2]);
}

assert(hash({1, 2, 3}) == hash({3, 2, 1}));
```

It is unclear to me if something similar is possible with the opaque `HashState` class.

**Comment by vslashg** [comment]
We don't provide such an API yet, but this is a gap we're aware of.  I can report, at least, that we've done a fair bit of implementation work in this area internally.  My progress on it got stalled out by user code in our local depot that makes use of internal APIs that we will need to change.  This bug is a good reminder for me to pick this issue back up.

The proposed API in development looks like:
  HashState::combine_unordered(state, it_begin, it_end)

and behaves much as you suggest.

(Note that xor is not an ideal state mixing operation, since it works badly with multisets.  We have been looking at addition, with the carry bit being re-inserted back into the state.)

**Comment by qnzhou** [comment]
Thanks @vslashg !  It is great to hear that this issue is being addressed!  A built-in `HashState::combine_unordered` is exactly what we need.

**Comment by vslashg** [comment]
I'm happy to report that this has landed.  stdlib hash tables and SwissTable types are now hashable by absl::Hash out of the box, and you can use `combine_unordered` to write `AbslHashValue` implementations for unordered collections of your own.
