### ISSUE TITLE
Workaround for missing -l option in libraries

### ISSUE THREAD

**Issue by ark-tik** [abseil/abseil-cpp#1164]
Hi,

Package config files generated by grpc does not include -l option for these libraries `advapi32`, `dbghelp` and `bcrypt`. Currently grpc generates these library names within quotes `""` rather than with a `-l` option. Which makes linking to these libraries errorneous.

I tried to look for underlying issue. And I think the issue is probably with this `$<JOIN:${ABSL_CC_LIB_LINKOPTS}, >` here [grpc-1.45.2/third_party/abseil-cpp/CMAKE/AbseilHelpers.cmake](https://github.com/abseil/abseil-cpp/blob/215105818dfde3174fe799600bb0f3cae233d0bf/CMake/AbseilHelpers.cmake#L182).

And the affected pkgconfig files are the only ones which adds libraries using `${ABSL_CC_LIB_LINKOPTS}` that too within quotes `""` as opposed to followed by `-l` option. Just for records the effected files are `absl_base.pc`, `absl_symbolize.pc` and recently added `absl_random_internal_seed_material.pc` with `"advapi32"`, `"dbghelp"` and `"bcrypt"` libraries respectively.

Can you please give a workaround for this or a correct way to use .pc files which does not include -l option with the mentioned libraries?

**Comment by suertreus** [comment]
I think this is fixed by 1963f10.

If not, please post more information about what platform you're building on and how to reproduce the problem.

**Comment by ark-tik** [comment]
Thanks for taking action on this. I haven't tested the changes but this is how the issue mentioned was reproduced earlier on windows platform using msys-mingw-64bit terminal.
1. Open `MSYS2 MinGW 64-bit` terminal on Windows 10 OS
2. Run `pkg-config --libs grpc`
3. In the output string notice the libraries such as `advapi32`, `dbghelp`, `bcrypt` without `-l` prefix.

Those missing `-l` prefix causes error upon using `pkg-config --libs grpc` command to fetch `grpc` libraries in `make` workflow.

**Comment by rpjohnst** [comment]
This change has made its way into MSYS's package, but it didn't solve the problem. Building with CMake as done [here](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-abseil-cpp/PKGBUILD) still produces `.pc` files with quoted rather than `-l`-prefixed names.

The change in https://github.com/abseil/abseil-cpp/commit/1963f10ae5cb32a7ea6d96b928f69d3c7fba0139 addressed a slightly different issue that doesn't look related. The fix here looks like it should just be to change the `$<$<BOOL:${MINGW}>:"bcrypt">` generator expressions to use the `-l` form?
