### ISSUE TITLE
Why absl::InlinedVector::data contains branch?

### ISSUE THREAD

**Issue by MBkkt** [abseil/abseil-cpp#1165]
Why not implemented as pointer to data? Like libstdc++ sso string

I understand why for string it's a one of options (libc++ for example):
We choose between sso size (additionally 7 chars) and data without branch

But InlinedVector commonly bigger than 3 word, and commonly sizeof(T) bigger than 1 byte?

Other implementation also make this optimization:
https://github.com/llvm/llvm-project/blob/main/llvm/include/llvm/ADT/SmallVector.h#L249 
https://github.com/boostorg/container/blob/develop/include/boost/container/small_vector.hpp

**Comment by CJ-Johnson** [comment]
This is something we've discussed a lot over the years. As you mentioned, there is prior art both for caching the branch (libstdc++ std::string) and not caching the branch (libc++ std::string).

The current consensus seems to be the following: InlinedVector is intended to be used in cases where the inlined case is most common. As a result, the branch should be well predicted, and speculative execution should provide most of the benefit of a cached data pointer. In exchange, by not caching the pointer, we get to shrink the size of the type. This is likely more valuable in the case of std::string, since it is more commonly used at interface boundaries. But it still has an effect on stack sizes, especially for recursive functions.

Thanks for the question!

**Comment by MBkkt** [comment]
@CJ-Johnson 
What do you think about compile time option(bool template parameter for example) for choose implementation?
I think I can try to implement it in some weekend
