### ISSUE TITLE
Unable to install absl at HEAD using homebrew

### ISSUE THREAD

**Issue by sandwichmaker** [abseil/abseil-cpp#1262]
**Describe the bug**

When trying to install absl-cpp using homebrew, the install fails with a cmake related error.

```
 ~: brew install abseil --head
==> Cloning https://github.com/abseil/abseil-cpp.git
Updating /Users/sameeragarwal/Library/Caches/Homebrew/abseil--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 92fdbfb3 Release the Abseil Logging library
==> cmake .. -DCMAKE_INSTALL_RPATH=@loader_path/../lib -DCMAKE_CXX_STANDARD=17 -DBUILD_SHARED_LIBS=ON
Last 15 lines from /Users/sameeragarwal/Library/Logs/Homebrew/abseil/01.cmake:

    GTest::gmock

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  absl/log/CMakeLists.txt:514 (absl_cc_library)


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

```
**Steps to reproduce the bug**
```
brew install abseil --head
```
**What version of Abseil are you using?**

https://github.com/abseil/abseil-cpp/commit/92fdbfb301f8b301b28ab5c99e7361e775c2fb8a

**What operating system and version are you using**
```
21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64
```

**What compiler and version are you using?**
```
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
Please include the output of `gcc -v` or `clang -v`, or the equivalent for your
compiler.
```
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
**What build system are you using?**

```
cmake version 3.24.1
```

**Comment by derekmauro** [comment]
https://github.com/abseil/abseil-cpp/blob/92fdbfb301f8b301b28ab5c99e7361e775c2fb8a/absl/log/CMakeLists.txt#L514-L537

https://github.com/abseil/abseil-cpp/blob/92fdbfb301f8b301b28ab5c99e7361e775c2fb8a/CMake/AbseilHelpers.cmake#L100-L103

It looks like we have our CMake setup so that we build all libraries that are marked `TESTONLY` and `PUBLIC` by default. The `TESTONLY` libraries often depend on GoogleTest, but you usually don't have GoogleTest unless you intend to build the tests, which isn't the default. I'm thinking we should maybe add a CMake option to build the test helpers (without running the tests) that is off by default.

It also looks like we have no build that doesn't run the tests, so we don't catch this issue. Ironically, running the tests caused us not to catch this.

**Comment by sandwichmaker** [comment]
I have googletest installed via homebrew too.

**Comment by derekmauro** [comment]
> I have googletest installed via homebrew too.

I think Abseil doesn't know to look for it unless you set the CMake flag to build the tests.
