### ISSUE TITLE
absl::SetStderrThreshold does not cause the FLAGS_stderrthreshold flag value to change

### ISSUE THREAD

**Issue by matta** [abseil/abseil-cpp#1266]
**Describe the bug**

In a command line utility I've written I'm using Abseil logging and flags. It makes no sense for this utility to ever log to anyplace but stderr, so I'd like to change the (effective) default value of FLAGS_stderrthreshold to zero. However, I can't figure out a way to do this in a satisfying way.

**Steps to reproduce the bug**

As far as I can tell, my two options are:

1. Call `absl::SetStderrThreshold(absl::LogSeverityAtLeast::kInfo);` early, before `absl::ParseCommandLine` and `absl::InitializeLog`. The problem with this approach is that this new value is not reflected in the flag, and this is exposed when the user passes `--helpfull`, which tells the user the default value of the flag is 2 (despite the effective value being zero, as this is what `absl::StderrThreshod()` is returning).
2. Call `absl::SetFlag(&FLAGS_stderrthreshold, 0)`. This keeps the flag and the global var that holds the value the logging library actually uses in sync, and the help text displays that the current value is `default: 2; currently: 0`, which I can live with. I'd rather see `default: 0` but that is a minor thing. However, to do this I must also `ABSL_DECLARE_FLAG(int, stderrthreshold);`, which is a bad idea -- for one, [absl/log/flags.h](https://github.com/abseil/abseil-cpp/blob/43d3c7a4e290ee96684735daf7b1d528c30a7943/absl/log/flags.h#L26-L27) does not advertise the type of the flag, just its name, so there is no way for me to declare it myself without making assumptions.

Possible fix:

Maybe a call to `absl::SetFlag(&FLAGS_stderrthreshold, absl::StderrThreshold())` belongs in `SyncLoggingFlags()` in [absl/log/flags.cc](https://github.com/abseil/abseil-cpp/blob/43d3c7a4e290ee96684735daf7b1d528c30a7943/absl/log/flags.cc#L40-L41)?

**What version of Abseil are you using?**

92fdbfb301f8b301b28ab5c99e7361e775c2fb8a (the "Release the Abseil Logging library" commit)

**What operating system and version are you using**

n/a

**What compiler and version are you using?**

n/a

**What build system are you using?**

n/a

**Additional context**

I am very happy Abseil logging was released at long last!

**Comment by rogeeff** [comment]
This issue was discussed at length during the release process and in fact we were initially planning to do this, but... Internally flag value affects nothing, but only updates the Logging library global. The Logging library is only controlled by the global value. There are various internal complications with trying to keep the value of the global config parameter and flag in sync. So we opted not to try to do it. This might change in the future, but not anytime soon (think years). For now, if you want to change the Logging library behavior programmatically, use the provided Logging globals API. if you want to change it at runtime - use flags. We do not even expose flags declaration specifically to emphasize this point.

There is indeed a minor issue that flag value does not represent the current state of the logging library, but I need to see  some evidence this is actually hurting usability. Additionally you can always use a custom usage message and notify the users about the fact that logging happens in stderr.

**Comment by matta** [comment]
Thanks @rogeeff, makes sense!
