### ISSUE TITLE
Apis for CamelCase() SentenceCase() etc in the Strings library?

### ISSUE THREAD

**Issue by pkbehera** [abseil/abseil-cpp#1274]
We implement such APIs many times for strings and use them.

Will it make sense to add these in abseil-cpp?

**Comment by derekmauro** [comment]
This is sort of answered in https://github.com/abseil/abseil-cpp/blob/master/FAQ.md#is-abseil-the-right-home-for-my-utility-library

We do provide APIs for ASCII upper case and lower case because those are very common and well-defined operations. Anything more complicated is less well-defined and may also show bias towards English. I'm not sure what your use case is, but the pro way of doing this might be to use a specialized internationalization library like ICU or something like gettext.

**Comment by pkbehera** [comment]
such APIs can be called AsciiCamelCase(), AsciiSentenceCase() etc., is the bias towards English language is to be indicated, just like how the APIs for upper/lower case.
