### ISSUE TITLE
The abseil flag library doesn't handle flags with dashes ('-')

### ISSUE THREAD

**Issue by jleconte2** [abseil/abseil-cpp#1320]
The abseil flag library doesn't handle flags with dashes ('-').

A lot of existing systems have flag names with dashes and it makes it hard to migrate to abseil flag or have flags passed from one system to another.

Would it be possible to do something similar to https://docs.python.org/dev/library/argparse.html#dest:
"Any internal - characters will be converted to _ characters to make sure the string is a valid attribute name".

**Comment by derekmauro** [comment]
Sorry, we have no plans to do this.

Abseil contains many of Google's core libraries, including our commandline flags library. This library is approximately 20 years old. We open-sourced Abseil so that Google code that was using this library could also be open-sourced. We didn't open-source Abseil in hopes that non-Google projects would also migrate to it. While we do hope that Abseil is also useful to the C++ community at large, the proposed change could impact our production users in ways that are hard to imagine. For this reason, this would be an expensive change for us to make, and we would only consider a change like this if it were critical to our needs.

**Comment by jleconte2** [comment]
Thanks for the quick answer !
Could you give an example on how such change "could impact our production users in ways that are hard to imagine" ?
I lack imagination to see how such a change would impact existing code.

**Comment by derekmauro** [comment]
From https://www.hyrumslaw.com/
> even the simplest library change caused failures in some far off system

So, no, I won't try to give you an example. As I said, we will not consider this change because our experience tells us this will break something, and we won't investigate what it will break without a critical motivation.
