### ISSUE TITLE
How do you automate the LTS version inline namespaces?

### ISSUE THREAD

**Issue by Sarcasm** [abseil/abseil-cpp#133]
Sorry if this question is out of place, but looking at the LTS branch and your LTS documentation, I can see the addition of the `inline namespace lts_2018_06_20 {` and `}  // inline namespace lts_2018_06_20` lines.

I was wondering how you performed this change?
Is it a sed-based tool (which I imagine could work somewhat reliably, seeing how the `absl` namesping is opened and closed in a consistent style)?
Is it a clang-based tool? If yes, any chance to open source it?

It looks like it could be an interesting refactoring tool, for example when vendoring a third party library.

**Comment by derekmauro** [comment]
The tool we used is actually opensource: https://github.com/google/copybara

In this particular case, we do use a very simple rule that relies on the `absl` namespace being opened and closed in a consistent style.

**Comment by mbxx** [comment]
Had we done this with a clang-based tool, we certainly would have tried to push it upstream to LLVM.

Interestingly, a clang-based refactoring tool wouldn't have quite worked for us out-of-the-box because of preprocessor directives like the one at https://github.com/abseil/abseil-cpp/blob/lts_2018_06_20/absl/types/variant.h#L48.  They only consider the abstract syntax tree, but because `namespace absl` appears in both branches of that `#ifdef`, one of the `namespace`s in that file is guaranteed not to make it into the AST.

**Comment by Sarcasm** [comment]
Thank your for your answer.
I actually looked if "copybara" was a thing, seeing the commit message was "Project import generated by Copybara.", but somehow I missed the project on Github.

**Comment by 9182850804** [comment]
ศักดิ์ชัย
