### ISSUE TITLE
Abseil_cpp failed to run 2 tests absl_notification_test and absl_time_test with release configuration and debug configuration with MSVC on windows

### ISSUE THREAD

**Issue by fangzhouxia** [abseil/abseil-cpp#1342]
### Describe the issue

Abseil_cpp failed to run 2 tests absl_notification_test and absl_time_test with release configuration and debug configuration with MSVC on windows. Could you please help take a look at this? Thanks in advance!

### Steps to reproduce the problem

1. open VS2019 x64 tools command
2. git clone --recursive https://github.com/abseil/abseil-cpp F:\gitP\abseil\abseil-cpp
3. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=amd64
4. cd F:\gitP\abseil\abseil-cpp & mkdir build_amd64 & cd F:\gitP\abseil\abseil-cpp\build_amd64
5. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DBUILD_TESTING=ON -DABSL_BUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release -DABSL_USE_GOOGLETEST_HEAD=ON .. 
6. msbuild /m /p:Platform=x64 /p:Configuration=Release absl.sln /t:Rebuild
7. ctest --build-config Release --output-on-failure

### What version of Abseil are you using?

Master branch,
commit is 1063d2b

### What operating system and version are you using?

Windows server 2019

### What compiler and version are you using?

VS2019(16.11.20)

### What build system are you using?

None!

### Additional context

[test.log.2.log](https://github.com/abseil/abseil-cpp/files/10206427/test.log.2.log)

**Comment by derekmauro** [comment]
absl_time_test is failing because it can't find the timezone data on your system. Set the TZDIR environment variable to point to the testdata to fix it. Something like `TZDIR=%CD%\absl\time\internal\cctz\testdata\zoneinfo` is what you need.

Some of our timing tests like Notification are known to be flaky. The error message shows a small difference: 49.8ms vs 48.4577ms. This is likely safe to ignore.
