### ISSUE TITLE
HexStringToBytes vs invalid input?

### ISSUE THREAD

**Issue by OlafvdSpek** [abseil/abseil-cpp#141]
The HexStringToBytes 'doc' doesn't define what happens on invalid input.

```
// HexStringToBytes()
//
// Converts an ASCII hex std::string into bytes, returning binary data of length
// `from.size()/2`.
std::string HexStringToBytes(absl::string_view from);
```

**Comment by zhangxy988** [comment]
As far as I can tell, the function doesn't validate the input, so the behavior is undefined.
I think we might want to update the documentation to state that the precondition should be "valid input".

**Comment by OlafvdSpek** [comment]
> so the behavior is undefined.

I don't think that's reasonable.

**Comment by tituswinters** [comment]
That does seem ... awkward.  I suspect we could get away with something more concrete and actionable - even returning an empty string would be a better signal.

**Comment by OlafvdSpek** [comment]
Interface consistency with Base64Unescape might be nice.

**Comment by zhangxy988** [comment]
@mbxx: It seems changing the interface of `HexStringToBytes` would be a breaking change. Maybe we could consider providing a "Safe" version of `HexStringToBytes` or return empty string upon invalid input?

**Comment by mbxx** [comment]
I definitely agree that `HexStringToBytes` is particularly awkward when it comes to handling invalid inputs.  I'd like to see if there's something we can do about that.

I think my ideal would be to change the signature of `HexStringToBytes` so that it can report errors.  I've started a conversation with the other (internal) owners of this code to see what they think.

It's worth pointing out that `Base64Unescape` and `CUnescape` are inconsistent with each other when it comes to how they handle invalid inputs and all of these functions have a sizable number of callers.  Making everything completely consistent would take some time, but we can probably do something to improve `HexStringToBytes`.

**Comment by mbxx** [comment]
Apologies for the long silence.  We talked about this and seem to generally agree that we should add an overload that has error reporting along these lines:

```
ABSL_MUST_USE_RESULT bool HexStringToBytes(absl::string_view from, string* to);
```

`HexStringToBytes` is called in an awful lot of places inside of Google, and some of them are undoubtedly (though likely inadvertently) relying on the current strange behavior.  This would make changing `HexStringToBytes` very challenging, but providing an overload will at least allow callers to use a better API.

This may take a while to materialize.  As a team philosophy, we try very hard to only release code that has had extensive use in production.  We could create an overload and release it, but that would feel like compromising our team's values.  The best way forward would be to migrate a substantial portion of Google over to the error-checking overload before open sourcing it, but (again) that migration seems difficult.  I believe we'll find a way to migrate a significant fraction of the call sites over, but this will take a little while to sort out.

**Comment by rogeeff** [comment]
We still have this on out book. We have b/139340580 to track the progress.

**Comment by Zuzuyoti** [comment]
افتح اتسحب

في الثلاثاء، ٦ فبراير ٢٠٢٤ ٥:٣٥ ص copybara-service[bot] <
***@***.***> كتب:
