### ISSUE TITLE
[Bug]: "The fast GetCurrentTimeNanos() algorithm based on the cyclecounter" get wrong value when Windows resume from sleep.

### ISSUE THREAD

**Issue by Hezq** [abseil/abseil-cpp#1460]
### Describe the issue

We're using abseil library with gRPC library and sometimes our process hang for a long time after resuming from sleep state. Most of the time, the hang time length is equal to the time length from sleep to resume, which means if I put my computer to sleep for 30 minutes, I need to wait 30 minutes for my process to continue working after resuming from sleep.

I thought this is gRPC library's bug at first, after digging into the debug log, I found the problem is caused by the fast GetCurrentTimeNanos algorithm in absl/time/clock.cc. This function should return the current nano second count, but it will return the nano second count when the computer was put into sleep mode sometime.

I then rebuilt abseil with **-DABSL_USE_CYCLECLOCK_FOR_GET_CURRENT_TIME_NANOS=1**, and the hang didn't occur anymore.

You can also refer to this issue for more information: [https://github.com/grpc/grpc/issues/33037](url)

### Steps to reproduce the problem

I didn't write sample code to reproduce the problem. But I think the issue description should be enough.

### What version of Abseil are you using?

abseil-cpp-20210324.2

### What operating system and version are you using?

OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19045 N/A Build 19045
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free

### What compiler and version are you using?

MSVC 2019

### What build system are you using?

cmake version 3.21.4

**Comment by derekmauro** [comment]
It's a good point that this likely doesn't work if the OS goes to sleep. I think we should likely disable this by default. Users running servers or who otherwise know that sleep will never happen can consider turning it back on. Last I checked on Linux x86-64 with a vdso `clock_gettime`, the Abseil algorithm was about twice as fast, although it does introduce a significant amount of jitter into the timing. Both are still quite fast, and only programs that need the current time thousands of times per second are likely to benefit from this algorithm.
