### ISSUE TITLE
URLEncode / Decode

### ISSUE THREAD

**Issue by OlafvdSpek** [abseil/abseil-cpp#158]
URLEncode / Decode functions would be nice to have.

**Comment by tituswinters** [comment]
(Without making any promises)
Can you provide more detail for what you're looking for? I'm pretty sure we won't be publishing a URL type (at least not soon).

**Comment by OlafvdSpek** [comment]
Functionality like http://php.net/urlencode and http://php.net/urldecode. 
No URL type required / requested.

**Comment by tituswinters** [comment]
Oh, you just want encoding / decoding for query-string params?

**Comment by OlafvdSpek** [comment]
I'm afraid so. ;)

**Comment by mbxx** [comment]
The internal versions of these functions look broadly used enough that we'll probably want to release them at some point, but they're currently part of the URL class where they live alongside a bunch of closely-related but very rarely used functions.  There's some design work to be done to figure out how best to cleanly separate this.  I think that would most likely happen as a part of a larger project to release a URL class, which as @tituswinters notes, isn't something that's on our immediate radar.

So I'd guess we'll release this at some point, but I don't know when that would be.  Sorry :(

I've added this to our list of feature requests, and linked this issue so that it can be updated when there's more information.

**Comment by JonathanDCohen** [comment]
Closing this issue since it's been added to feature requests.  Please feel free to re-open :)

**Comment by jorgbrown** [comment]
You can get what you're asking for via a single call to absl::StrReplaceAll, like this:
```
const std::array<std::pair<absl::string_view, absl::string_view>, 25> kURLEncode =
    {{{" ", "%20"},   {"\"", "%22"}, {"#", "%23"}, {"$", "%24"},
      {"%", "%25"},   {"&", "%26"},  {"+", "%2B"}, {",", "%2C"},
      {"/", "%2F"},   {":", "%3A"},  {";", "%3B"}, {"<", "%3C"},
      {"=", "%3D"},   {">", "%3E"},  {"?", "%3F"}, {"@", "%40"},
      {"[", "%5B"},   {"\\", "%5C"}, {"]", "%5D"}, {"^", "%5E"},
      {"`", "%60"},   {"{", "%7B"},  {"|", "%7C"}, {"}", "%7D"},
      {"\177", "%7F"}}};

std::string AbseilEncodeURL(absl::string_view s) {
  return absl::StrReplaceAll(s, kURLEncode);
}
```
or
```
const std::array<std::pair<std::string_view, std::string_view>, 25> kURLDecode =
    {{{"%20", " "},   {"%22", "\""}, {"%23", "#"}, {"%24", "$"},
      {"%25", "%"},   {"%26", "&"},  {"%2B", "+"}, {"%2C", ","},
      {"%2F", "/"},   {"%3A", ":"},  {"%3B", ";"}, {"%3C", "<"},
      {"%3D", "="},   {"%3E", ">"},  {"%3F", "?"}, {"%40", "@"},
      {"%5B", "["},   {"%5C", "\\"}, {"%5D", "]"}, {"%5E", "^"},
      {"%60", "`"},   {"%7B", "{"},  {"%7C", "|"}, {"%7D", "}"},
      {"%7F", "\177"}}};

std::string AbseilDecodeURL(absl::string_view s) {
  return absl::StrReplaceAll(s, kURLDecode);
}
```

**Comment by bcsgh** [comment]
Any update? If it's going to be another 5+ years before a URL class gets published, then it might be worth the risk of speculating what a free function interface for this would look like and releasing that sooner.
