### ISSUE TITLE
absl::Time and absl::Duration

### ISSUE THREAD

**Issue by weidonglian** [abseil/abseil-cpp#172]
Hi,

We start using the absl::Time and absl::Duration in our code base to handle time, duration, date, timezone formatting. 
1. Is the absl::Time is monotonic? Can we use it to schedule the task or job running?
I know you have ClockTime which is internal API ( I guess it is not encouraged to be used outside of abseil). 
2. How you handle it if the user changes the local system time or Daylight time change? Will your absl::Time be reflected without restarting the user's computer? (Since I noticed in your implementation, you try to fetch from the cpu clock and then do some approximation). 

Would be really appreciated if you could explain your design goal and potential side effects? This is not easy to find in the documentation.

Thanks
Weidong

**Comment by derekmauro** [comment]
`absl::Time` represents an absolute point in time, so "monotonic" in meaningless in reference to `absl::Time`. I think you mean to ask if `absl::Now()` is monotonic, and the answer is no, it isn't.

Changes to the system clock do not change stored `absl::Time` values. Values returned by `absl::Now()` will jump around if the user changes the system clock. Time changes will be reflected by `absl::Now()` very shortly after changes to the system clock happen. You don't have to restart the program.

If you are trying to measure a time interval, I'd recommend you use `std::chrono::steady_clock`.

For scheduling tasks, I think this comment in [`pthread_cond_timedwait(3)`](https://linux.die.net/man/3/pthread_cond_timedwait) is relevant:
>An absolute time measure was chosen for specifying the timeout parameter for two reasons. First, a relative time measure can be easily implemented on top of a function that specifies absolute time, but there is a race condition associated with specifying an absolute timeout on top of a function that specifies relative timeouts. For example, assume that clock_gettime() returns the current time and cond_relative_timed_wait() uses relative timeouts:
```
clock_gettime(CLOCK_REALTIME, &now)
reltime = sleep_til_this_absolute_time -now;
cond_relative_timed_wait(c, m, &reltime);
```
>If the thread is preempted between the first statement and the last statement, the thread blocks for too long. Blocking, however, is irrelevant if an absolute timeout is used. An absolute timeout also need not be recomputed if it is used multiple times in a loop, such as that enclosing a condition wait.
>
>For cases when the system clock is advanced discontinuously by an operator, it is expected that implementations process any timed wait expiring at an intervening time as if that time had actually occurred.

It looks like the time documentation hasn't been published yet, but I'm pretty sure it is in the works. In the mean time, you might want to review [Greg Miller's CppCon talk about time fundamentals](https://www.youtube.com/watch?v=2rnIHsqABfM) since he is one of the designers of this library.

**Comment by shaindelschwartz** [comment]
For additional documentation, the [Time programming guide](https://abseil.io/docs/cpp/guides/time) is now available.

**Comment by weidonglian** [comment]
> For additional documentation, the [Time programming guide](https://abseil.io/docs/cpp/guides/time) is now available.

Great, thanks for the documentation!!
