### ISSUE TITLE
How to enable sse in the new hash tables?

### ISSUE THREAD

**Issue by wjywbs** [abseil/abseil-cpp#178]
Since the public hash table headers include the internal raw_hash_set.h, how should the sse instructions in raw_hash_set.h be enabled? All cc targets using the new hash tables will need a copt like `-mssse3`.

Or is the speed difference insignificant between the sse and non sse versions?

https://github.com/abseil/abseil-cpp/blob/master/absl/container/internal/raw_hash_set.h#L94
https://github.com/abseil/abseil-cpp/blob/master/absl/container/flat_hash_map.h#L40
https://github.com/abseil/abseil-cpp/blob/master/absl/container/BUILD.bazel#L450

**Comment by derekmauro** [comment]
We can't put something like `-msse3` in `ABSL_DEFAULT_COPTS` because we don't know if you are building for a CPU that supports SSE3. You either have to add it to your `CROSSTOOL` file or specify it on the command line. I think `--copt=-march=native` will set it correctly for the machine you are compiling on, but keep in mind the architecture of the machine you are compiling on may not be the same architecture as the machine you plan to deploy on.
