### ISSUE TITLE
Xcode 10 libc++ and backwards compatiblity

### ISSUE THREAD

**Issue by teki** [abseil/abseil-cpp#207]
Environment:
OS: macOS 10.13.6
Compiler: Xcode 10, clang-1000.11.45.2
Relevant compiler flag: `-std=c++1z`

Got this error
```
webrtc/modules/rtp_rtcp/include/rtp_rtcp_defines.h:83:12: error: call to unavailable function 'get': introduced in macOS 10.14
    return absl::get<VideoPayload>(payload_);
```
I guess the checks in `config.h` are not strict enough for this combination.
The type of `payload_` is:
```
  absl::variant<AudioPayload, VideoPayload> payload_;
```

**Comment by JonathanDCohen** [comment]
Sorry it took so long to get to this.  It seems like you're using -std=c++1z but std::get isn't available anyways.  Let me try to reproduce this on our end and fiddle with our config settings to see if I can't get a workaround for you.

**Comment by JonathanDCohen** [comment]
Interestingly it looks as though this is not in compliance with Apple's release notes which say that <any>, <optional> and <variant> should be supported in xcode 10 period.  I'm still trying to find how to detect macOS version computationally

**Comment by Bart-Frankenfield** [comment]
I'm not sign into my Microsoft account at this time I know you want to be working I would appreciate the work being done but if you want me to sign into my Microsoft account I can my Chrome book is down I need gigabytes on the hard drive so please

**Comment by Bart-Frankenfield** [comment]
Sent from Mail for Windows 10

**Comment by despair86** [comment]
~~currently working on a codebase that switched to abseil 12-12-18 LTS.~~

~~the current macintosh version macros effectively disable support for *all other platforms* that otherwise have C++17.~~

~~tested: G++ 7.3, for `i686-w64-mingw32` in `-std=c++1[z7]` mode~~

i'm an idiot: the GNU tools are not officially supported for abseil (even with `clang-cl(1)` in UNIX mode) 🤦🏻‍♂️, but my projects moved off of Microsoft C++ ages ago because some of them still support positively _ancient_ Win32 targets. don't ask why.

**Comment by teki** [comment]
There are some macros in libcxx to handle this: https://github.com/llvm-mirror/libcxx/blob/2ae08ad852f35bfff251e4332a122a07013c8bed/include/__config#L1322
Not sure if they can help with detection.
