### ISSUE TITLE
`operator<<` vs `Do not depend on ADL`

### ISSUE THREAD

**Issue by mdrost** [abseil/abseil-cpp#21]
Abseil provides bunch of `operator<<(std::ostream& o, ...)` for various types. Am I not supposed to use them to conform to Abseil Compatibility Guidelines?

**Comment by zhangxy988** [comment]
For steam operators, you have to depend on ADL or they are useless.
We will update the Compatibility Guidelines to make it more clear, i.e. "Do not depend on ADL if you don't have to".

**Comment by tituswinters** [comment]
Maybe something like:

Some APIs are designed to work via ADL - operator<< for iostreams, unqualified swap in generic code, etc.  For the majority of APIs, ADL isn't really part of the design. Calling functions from namespace absl via ADL when they do not intend that must be avoided.  This is especially true for any function that accepts a pre-adopted type like absl::string_view: when the type changes because of availability of the std-version of the same, the associated namespaces will change and the ADL lookup will fail, resulting in build breaks for you.

**Comment by zhangxy988** [comment]
Updated in https://github.com/abseil/abseil.github.io/pull/59.
