### ISSUE TITLE
Print functions without format

### ISSUE THREAD

**Issue by wjywbs** [abseil/abseil-cpp#212]
Is there any print function without formatting string, like StrCat but outputting to stdout?

**Comment by JonathanDCohen** [comment]
We will be releasing a logging library soon, hopefully by the end of Q4 this year.

Is there a reason why any of the format string APIs or `std::cout << StrCat(a, b, c)` don't work?  As in something like

`std::cout << absl::StreamFormat("%s", MyStringThing());`

**Comment by wjywbs** [comment]
I'm using `std::cout << StrCat(a, b, c)` now, but I was trying to avoid allocating a string and output to stdout piecewise, like PrintF.

**Comment by mbxx** [comment]
We don't have a StrCat that writes to stdout, and we don't have any plans to offer something like that, unfortunately.

I'm probably missing something really obvious, but I naively would have thought that anything you could pass into StrCat you could also pass directly to std::cout.  Are you using StrCat for hex formatting?

Personally, I wouldn't worry too much about a string allocation when writing to stdout because the cost of the allocation is probably much less than the cost of the I/O.  If the cost of the allocation is an issue for you and you'd still like to use something like StrCat, you do have the option of writing your own functions that have absl::AlphaNum parameters.  Something along these lines this should work:

```
void WriteToStdout(absl::AlphaNum a, absl::AlphaNum b, absl::AlphaNum c) {
  std::cout << a.Piece() << b.Piece() << c.Piece();
}
```

Clearly this isn't as convenient as having something you can use out-of-the-box, but you may find it useful in some situations.

**Comment by wjywbs** [comment]
I will use the WriteToStdout example above when necessary. Thanks.

**Comment by Bart-Frankenfield** [comment]
Right now I can't figure out how to reuse my reader reader and writer so I outlook but come back again really honestly my Google Chrome is down I have no gigabytes on the hard drive on it will be it will probably be mid December before I get that up And

**Comment by Bart-Frankenfield** [comment]
Only the icons up until the 30th and that way you guys could work on it I'll just keep it on my browser Thanks a lot

**Comment by Bart-Frankenfield** [comment]
I’ll keep the browser up Until the 30th That way you guys can work on it Thanks a lot Send me an email if you Need to

Sent from Mail for Windows 10
