### ISSUE TITLE
Abseil fails to build since commit f6ae816 (Nov 16, 2018)

### ISSUE THREAD

**Issue by vehystrix** [abseil/abseil-cpp#221]
Since commit f6ae816, abseil fails to build.

I suspect the following internal commit may be at the source of the issue:

> f4044c56d44ba0ac2a9f218ed55f1b1f9e985eae by Abseil Team <absl-team@google.com>:
> 
> Update absl/base/CMakeLists.txt to use new functions
> i.e. absl_cc_(library|test)
> 
> PiperOrigin-RevId: 221676669
> GitOrigin-RevId: da04b8cd21f6225d71397471474d34a77df0efd6
> Change-Id: If6621e10d096a39b6a056a072c2727a0df0b0620

Attached is the output for a build starting in an empty folder, with no extra options passed to CMake.
[abseil_build_output.txt](https://github.com/abseil/abseil-cpp/files/2598864/abseil_build_output.txt)
The problem reproduces in Visual Studio 2017 as well

**Comment by derekmauro** [comment]
@JonathanDCohen @Mizux Is there a way to exclude absl/base/spinlock_test_common from being built when testing isn't requested? It's really a test only library that depends on gtest.

**Comment by Mizux** [comment]
Hi,
 sorry for the delay
simply repace `PUBLIC` by `TESTONLY` here (at bottom line 266)
https://github.com/abseil/abseil-cpp/blob/3088e76c597e068479e82508b1770a7ad0c806b6/absl/base/CMakeLists.txt#L253-L267

note: This target is only used for testing purpose for absl or as helper for your own test that 's why it has been set PUBLIC but since it depends on GoogleTest it should be PUBLIC only if Target gtest is available...
