### ISSUE TITLE
Allow custom base in SimpleAtoi?

### ISSUE THREAD

**Issue by wjywbs** [abseil/abseil-cpp#233]
The SimpleAtoi function always parses the string in base 10. Can an optional base argument be added?

https://github.com/abseil/abseil-cpp/blob/master/absl/strings/numbers.h#L179

**Comment by mbxx** [comment]
The short answer is maybe eventually, but not soon.

Our goal for SimpleAtoi is to keep it as simple as possible, but it's clear that it doesn't handle all of the number parsing needs that someone may have.  As you point out, it doesn't allow alternate bases to be specified.  It also won't detect the base for strings like "0xabc".  Another common case is parsing a leading number from a string, and SimpleAtoi doesn't handle that, either.  It would be nice if we had a more general-purpose solution for these cases.

Adding an optional parameter to SimpleAtoi is one possible approach, but we'd really like to keep it the way it is to keep it as simple as possible.  To address the more general number parsing cases, we'd rather introduce a new API.

That's not something we're working on right now, though, because we're currently trying to release libraries that are much more widely used at Google.  It turns out in practice that parsing a number in base 10 handles about 95% of the cases, by which I literally mean it occurs 20x more often in our codebase.

So we know there's a feature gap here, but because SimpleAtoi covers 95% of the cases, it's going to be a while until we come back around to it.

**Comment by JonathanDCohen** [comment]
Closing as wontfix since we aren't actively working on this.  Please feel free to re-open :)
