### ISSUE TITLE
export commits individually

### ISSUE THREAD

**Issue by benjaminp** [abseil/abseil-cpp#246]
Each internal export of Abseil appears to make just one commit in the git repository. For example, 44b0fafc62d9b8f192e8180cbe9c4b806b339d57 aggregates some 19 separate commits. While it's usually possible to match up the code change to commit message, it would be better for git repository usability if individual Piper changes became individual git commits.

**Comment by derekmauro** [comment]
I agree it would be better if this were the case.

If you are wondering why we do it this way, it has to do with how we develop code internally. The code you see in our git repository isn't exactly the same as the code we use and develop everyday internally. We use a tool called [Copybara](https://github.com/google/copybara) to transform the internal version of the code to what you see on GitHub. While differences in the transformed code are very minor, we still need a human to look at all the code we push here, since at code review time we are only reviewing the internal version of the code. In our current workflow, we try to export the code once every business day, and it is setup so that we only have to review one squashed change instead of many individual changes.

It's unlikely that this will change anytime soon, but if we ever redesign our workflow from scratch, we will consider it.

**Comment by benjaminp** [comment]
Why would your workflow have to be redesigned from scratch? It seems to me reviewing a batch of commits once and exporting them individually should be technically feasible.

**Comment by JonathanDCohen** [comment]
As of now we aren't actively working on batching our commit messages.  I'm going to assign this to myself because I'm curious if we could do this without affecting the time of the release process too much, but as a low priority project.  If I take a look and it looks like it will take too much time compared to the benefit, then I'll close the issue until we find the time to take another look.

**Comment by acmorrow** [comment]
I'd also like to see this fixed. While the fix for #355 was much appreciated, it comes along with another change that we don't need. It leaves us in a position where we can't easily cherry-pick the fixing commit into our currently vendored copy of abseil without dragging in the other work.

**Comment by derekmauro** [comment]
I don't think this is going to be fixed.

Abseil's source of truth is our internal code repo, we just export the code here as a squash commit. Some transforms do happen when the code is released. A human has to review the squash commit to ensure we aren't leaking any info that we shouldn't be leaking. If there is anything that shouldn't be released, we fix that by submitting another change to the internal repo. Anything other than a squash commit would leak that info in one of the incremental commits.

Unfortunately fixing this would put additional burden on reviewers. They would have to both understand open source policies and review the transformed code as well. We found that simply more scalable to have a reviewer familiar with these policies to review the transformed code once a day.

This could change, but currently we have no plans to alter our release process.

**Comment by HenryRLee** [comment]
@derekmauro Actually that can be prevented by interactive rebase (`git rebase -i`). But still that is additional burden to the maintainers.
