### ISSUE TITLE
absl::StrFormat() docs

### ISSUE THREAD

**Issue by OlafvdSpek** [abseil/abseil-cpp#258]
> error: ‘StrFormat’ is not a member of ‘absl’

Could the `#include` be included? ;)

> // Won't compile, not constexpr (and strings can't be declared constexpr).
> std::string formatString = "Welcome to %s, Number %d!";
> std::string s = absl::StrFormat(formatString, "The Village", 6);

> // This will compile.
> constexpr absl::string_view formatString = "Welcome to %s, Number %d!";
> string s = absl::StrFormat(formatString, "The Village", 6);

Why is `std::` used inconsistently?

https://abseil.io/docs/cpp/guides/format#abslstrformat

**Comment by derekmauro** [comment]
It's probably a copy-paste error in the documentation. At Google, for historical reasons `string` is not the same type as `std::string`. https://www.youtube.com/watch?v=NzaYUlAw93k tells the story if you are interested. I'll get the docs fixed.

**Comment by ericderojas** [comment]
I know I'm a little bit behind the times. I'm not shy so I would say
your noncompete is due to trying to get it to go too fast.  If you need it
to that it just needs more muscle. If may say if you remove all your jocks.
It might work, have fun time to sleep. :) make show the strings too much;)
can you see, as to your (Q) you're are, sww, see

*Eric de Rojas  *

*Live in Peace *

**Comment by JonathanDCohen** [comment]
Didn't realize this would be closed from the comment.  I'll close once that PR is accepted

**Comment by OlafvdSpek** [comment]
@JonathanDCohen Note the `#include` request as well. ;)

**Comment by OlafvdSpek** [comment]
@manshreck What about the `#include`?

**Comment by OlafvdSpek** [comment]
@JonathanDCohen What about the `#include`?
