### ISSUE TITLE
flat_hash_set iterator --operator

### ISSUE THREAD

**Issue by jcageman** [abseil/abseil-cpp#266]
absl::flat_hash_set::iterator (and const) doesn't support the --operator.

I already noticed this seems to be a difference between clang and msvc for std::unordered_set. The absl implementation seems to follow clang here.

The following code compiles for msvc (get iterator to the last element):
```
    std::unordered_set<std::string> testset;
    testset.insert("test");
    auto it = testset.end();
    --it;
```

See comparison of compilers and std::unordered_set vs absl::flat_hash_set below:

https://godbolt.org/z/45qeqY

**Comment by sbenzaquen** [comment]
Yes. Our iterators are only "forward iterators", not "bidirectional iterators".
Note that he spec for `std::unordered_*` only requires forward iterators.

In general, since the order is unspecified (and unstable for `flat_hash_*`), iterating "backwards" doesn't really have meaning. Providing bidirectional iterators has a cost (memory+cpu+code complexity) we are not willing to pay for the little benefit (if any) it gives.

**Comment by vslashg** [comment]
Working as intended.
