### ISSUE TITLE
MSVC lnk4221 with string_view.cc

### ISSUE THREAD

**Issue by libbooze** [abseil/abseil-cpp#277]
I do not have minimal self contained example so you will have to take my word for it.
string_view.cc has [#ifdef ](https://github.com/abseil/abseil-cpp/blob/256be563447a315f2a7993ec669460ba475fa86a/absl/strings/string_view.cc#L17)that basically deletes entire source file when std::string_view is available. 
This triggers stupid VC++ linker to issue warning since file is empty. 
There are workarounds on [StackOverllow ](https://stackoverflow.com/a/25422179/700825)that work(making a dummy function so that file is not empty), but I hope you could do some magic with your CMAKE configs to solve this elegantly. 

note: I did try passing ignore:4221 to linker, but for some reason that did not work, and anyway I would prefer not to loose the warning for the entire CMAKE build just so that 1 file in 3rd party problem is solved.

Also I do not want to open issue for other problem I have since I have seen this discussed before, but here is a cry for prioritization:
please make abseil warnings clear, it is quite irritating to deal with it in CMAKE. By this I am referring to build of abseil itself, not including abseil headers.

**Comment by JonathanDCohen** [comment]
We used to do cmake magic like this for header-only libraries, but that's neither here nor there since string_view has a source file.  I would assume we need a solution for Bazel as well, you don't happen to be able to try that are you?

For the second request, check out absl/copts/copts.py.  It's the source of truth for our compile options and will show you all the warnings and such we're currently compiling against

**Comment by libbooze** [comment]
Thank you for the reply.

I do not have access to basel, but my guess it would be same since it related to linker, so any build with that warning enabled and C++17 language option set should trigger this.

As for the second request:
I think the core problem is that abseil does not work nicely as subdirectory that inherits compile options from "above", in other words I do not know of any CMAKE way to remove warnings beside tedious -Wno-...
For the record this is what I ended up doing in the end, but it is not that nice, I would hope abseil could be configured to just compile without warnings regardless of what parent warnings are.
![image](https://user-images.githubusercontent.com/47703951/54383771-1bad7480-4693-11e9-9ca5-f17c04ebb258.png)

As a bonus you can see another issue: MSVC warns about deprecated type traits, so you may want to open an issue for that also(if you care to fix it, me personally would like it fixed, but it is not that critical since MSVC error gives you solution).

**Comment by rongjiecomputer** [comment]
Bazel build does not have that linker warning because `-ignore:4221` is added in CROSSTOOL by default.

https://github.com/bazelbuild/bazel/blob/5da1098f9a5c1f7f29922bce093b66c33cccd74b/tools/cpp/cc_toolchain_config.bzl.tpl#L708

LNK4221 warning is quite useless IMO. Many open source projects use this technique to choose implementation inside source files without having to if-else source files in build scripts. This make supporting multiple build systems a lot easier.

@libboze We can add `-ignore:4221` to `ABSL_CC_LIB_LINKOPTS`. Would that be enough for you?

**Comment by libbooze** [comment]
@rongjiecomputer I do not know, my CMAKE skills are very modest, but if you want you can tell me that the patch would be and I can do it myself and see if it removes 4221(after I remove dummy function in string_view.cc).

Also do you want me to make an issue about deprecation warning MSVC gives(you can see the macro to disable it in screenshot) or not? 
I am personally on a fence: it is irritating that abseil is not deprecation warning clean, but takes just 1 minute to fix.

**Comment by JonathanDCohen** [comment]
I can write an internal patch for this, but Cmake skills aren't that relevant here.  To change abseil compile options, you need to edit absl/copts/copts.py.  We also will need to change AbseilConfigureCopts.cmake and configure_copts.bzl to except the new options, since we don't currently configure link options with this tooling.
