### ISSUE TITLE
Incorrect max_load_factor() in raw_hash_set

### ISSUE THREAD

**Issue by greg7mdp** [abseil/abseil-cpp#289]
This returns a constant 1.0.
`float max_load_factor() const { return 1.0f; }`
Shouldn't it be 0.875?

**Comment by sbenzaquen** [comment]
There are cases where `load_factor` is `1`.
In particular, if you do `absl::flat_hash_set<int>{0}` you get a table with one element and one slot, so the load factor there is `1`.

**Comment by greg7mdp** [comment]
Seriously? that is seriously misleading. `max_load_factor()` is meant to be informative, and should not be obfuscated by corner cases.

The standard says: `Manages the maximum load factor (number of elements per bucket). The container automatically increases the number of buckets if the load factor exceeds this threshold.`.

With that understanding, max_load_factor() returning 1 would mean that the flat_hash_set will not resize until it is 100% full.

**Comment by sbenzaquen** [comment]
The standard says:

> Returns a positive number that the container attempts to keep the load factor less than or equal
> to. The container automatically increases the number of buckets as necessary to keep the load
> factor below this number.

This is still true for us.
But in general load factor is not something we can mimic exactly. For example, we can't let the user provide a max load factor. The standard assumes a closed addressing implementation, which allows for max load factors greater than `1`. That doesn't work for open addressing.

**Comment by greg7mdp** [comment]
> This is still true for us.

Yes, but this is not what the container actually does. For the cases that matter (i.e. when the container has more than a couple elements), the flat_hash_set increases the number of buckets if the load factor exceeds 0.875, not 1.  Returning 1 because it happens to be true for sets with 1 or 3 elements is misleading. Note that the standard never says that the load factor is never allowed to exceed the value returned by max_load_factor().

> The standard assumes a closed addressing implementation, which allows for max load factors greater than 1. That doesn't work for open addressing

Well, of course > 1 will not work. However you could allow to set a load factor between 0.5 and 0.875 in case someone is just concerned about speed, not memory.

**Comment by sbenzaquen** [comment]
> For the cases that matter (i.e. when the container has more than a couple elements), the flat_hash_set increases the number of buckets if the load factor exceeds 0.875, not 1.

Which still satisfies the spec. It doesn't say that it has to do it exactly when you are about to go above max load factor. It says that load factor will never be above max load factor.
I guess you can argue that is following the letter of the rule, and not the spirit.

> Well, of course > 1 will not work. However you could allow to set a load factor between 0.5 and 0.875 in case someone is just concerned about speed, not memory.

According to our experiments, that is not the case. Decreasing the max load factor actually caused the code to be slower, due to the extra memory pressure. The current probe algorithm is actually pretty good at delivering perfect probing (ie the object is on the first place we look). Depending on the distribution of the data and the load factor it can achieve between 90%~99.9%.
We removed this knob because we saw that the vast majority of uses were misguided.
Users can still call `reserve`/`rehash` if they really want a larger table, but we don't advise it in the common case.

**Comment by greg7mdp** [comment]
> It says that load factor will never be above max load factor.

where does it say that? 

> We removed this knob because we saw that the vast majority of uses were misguided.

OK, that makes sense
