### ISSUE TITLE
benchmark test not getting build with cmake

### ISSUE THREAD

**Issue by deryck1031** [abseil/abseil-cpp#295]
benchmark test cases arent getting build for cmake.  They are only part of the bazel build.  For example: mutex_benchmark is in BUILD.bazel, but not in CMakeLists.txt.  Can we please add them to cmake?

**Comment by derekmauro** [comment]
I don't think this is a request that we are going to prioritize at the moment for a couple reasons.

First, we use bazel for development so we already have a way to run these when we need to. We rarely run the benchmarks are part of our testing procedure anyway. We can usually judge when a change might have a performance impact and run it in those situations.

Second, while micro-benchmarks are useful, we ultimately validate changes to performance with macro-benchmarks, which compare the impact of changes to actual production programs in production workloads. This is because synthetic benchmarks often don't reflect the way modern hardware behaves.

If someone from the community wants to work on this, please comment here.
