### ISSUE TITLE
logging and flags support

### ISSUE THREAD

**Issue by lucasjinreal** [abseil/abseil-cpp#297]
abseil-py supports logging and flags, but why not support in cpp? Does it already supported? I can not found where to using it.

**Comment by derekmauro** [comment]
Flags and logging are not supported yet, but both are actively being worked on.

**Comment by lucasjinreal** [comment]
@derekmauro Thanks for your reply, I am happy hoping for that. So that we can integrate all useful tools into one single lib.

**Comment by cblichmann** [comment]
Flags are now released: https://abseil.io/blog/20190509-flags

**Comment by lucasjinreal** [comment]
@cblichmann  What about logging? Any schedual?

**Comment by cblichmann** [comment]
I'm not on the Abseil team, I just linked the blog post :)
@derekmauro, do you have some schedule you can share wrt logging?

**Comment by tituswinters** [comment]
Schedules are *really* hard in this space, because we're not just
developing a logging API, we're taking the thing that's used internally
*everywhere*, cleaning it up (any changes are going to be a lot harder once
its externalized), moving it into our internal copy of Abseil, fixing all
internal references to point to that ... and doing that without breaking
the internal Google developers. Seems like still probably 6 months off, but
could be a lot longer than that.

*From: *Christian Blichmann <notifications@github.com>
*Date: *Thu, May 9, 2019 at 10:51 AM
*To: *abseil/abseil-cpp
*Cc: *Subscribed

I'm not on the Abseil team, I just linked the blog post :)

**Comment by bsarden** [comment]
Now that this issue is closed, is there somewhere else where we can track the progress of logging support in abseil-cpp? I’m also curious about what the plans are for the CHECK macros that are currently part of glog. Would those macros still be part of the logging library going forward, or would they become something like an `//absl/check:check` Bazel target?

**Comment by suertreus** [comment]
I plan to ship `CHECK` in the same header and Bazel target as `LOG`, which I expect to be `absl/logging/logging.h` and `//absl/logging:logging`.

**Comment by bsarden** [comment]
Awesome thanks for the update! Is there any timeline for when we can expect the `//absl/logging:logging` target to be available?

**Comment by Mizux** [comment]
Why closing this issue since logging is still not available in abseil-cpp and AFAIK we may expect it ?

note: you should rename this double issues too...

**Comment by cblichmann** [comment]
They likely closed it because there exists an internal tracking bug for this and there will probably be some blog post announcing it when it becomes available.

(Note the use of "likely" and "probably", I can only guess how the Abseil team will actually release logging when it's finally ready)

**Comment by Mizux** [comment]
Primary issue of:
* https://github.com/abseil/abseil-cpp/issues/658
* https://github.com/abseil/abseil-cpp/issues/882
* https://github.com/abseil/abseil-cpp/issues/980
* https://github.com/google/glog/issues/564

**Comment by romange** [comment]
I hacked glog library to use absl instead of gflags. Here is how I import it: https://github.com/romange/helio/blob/master/cmake/third_party.cmake#L186

and here is the modified branch of glog: https://github.com/romange/glog/tree/Absl
