### ISSUE TITLE
Flags parse does not appear to work as is documented

### ISSUE THREAD

**Issue by photex** [abseil/abseil-cpp#304]
Howdy!

Was excited to try out the flags library. But I'm met rather quickly with confusion:

```
#include <absl/flags/flag.h>
#include <absl/flags/parse.h>
ABSL_FLAG(uint32_t, code, 0, "Optional integer value to include with the message.");

int main(int argc, char* argv[]) {
    absl::ParseCommandLine(argc, argv);

    return 0;
}
```

I just cloned this repo and tried to build this example using MSVC (Cmake). But so far, no flags appear to get defined:

```
.\target\dist\amd64-debug\bin\kmsg.exe --code
ERROR: Unknown command line flag 'code'

.\target\dist\amd64-debug\bin\kmsg.exe --help
ERROR: Unknown command line flag 'help'
```

I've been reading the blog post and the guide but I don't understand what I've done incorrectly.

**Comment by photex** [comment]
Just checked that it works on Linux but not on Windows.

**Comment by derekmauro** [comment]
I tested this on a Windows machine and it worked for me. Can you post a complete example, including your Cmake file? A link to a repo I can clone would be best.

**Comment by photex** [comment]
Thanks for looking into it @derekmauro. I've created a repo that replicates the issue: https://github.com/photex/abseil-flags-broken-example

**Comment by derekmauro** [comment]
Thanks, I've reproduced this issue.

The root cause is that [MSVC's implementation of `constexpr` is broken in Debug mode](https://developercommunity.visualstudio.com/content/problem/262083/compiler-emits-dynamic-initializer-for-variable-wi.html). If you test this in release mode, you will see that it works.

A patch is coming for this specific issue in the next release, but we are probably going to hit this problem in any code that relies on globals of Abseil's synchronization types (`absl::Mutex`, `absl::once_flag`, `absl::base_internal::SpinLock`, etc) in debug mode on Windows. We will need to address these issues as well.

**Comment by photex** [comment]
Cool, thanks for looking into it! Glad I could assist.
