### ISSUE TITLE
Missing exception specification

### ISSUE THREAD

**Issue by miscco** [abseil/abseil-cpp#325]
The move assignment operator of InlinedVector is missing an exception specification. As far as I know move operator/assignment are one of the places where it actually matters

https://github.com/abseil/abseil-cpp/blob/b1dd425423380126f6441ce4fbb6f8f6c75b793a/absl/container/inlined_vector.h#L495

Generally the exception specification should be equivalent to that of the move constructor, e.g
```cpp
InlinedVector& operator=(InlinedVector&& other) noexcept(
      absl::allocator_is_nothrow<allocator_type>::value ||
      std::is_nothrow_move_assignable<value_type>::value)
```
However, the `||` from the move constructor seems bogus. If the allocator would be nothrow then even a throwing move assignment would lead to a `noexcept(true)` specification. Shouldnt it be `&&` as we cannot determine which codepath is taken beforehand.

Is the exception specification of the move constructor correct or should it also be `&&`?

**Comment by CJ-Johnson** [comment]
Thanks for assigning @derekmauro 

@miscco Thanks for bringing this up! I agree that the state of the noexcept specifiers is not where it should be in InlinedVector. Auditing them and fixing them is on my TODO list.

Specifically for the move constructor, I believe you are correct. I noticed it recently as well and thought that it should be `&&` instead of `||` but I just hadn't gotten around to researching to confirm my suspicion.

I'll keep this issue open and update it as I make progress.

**Comment by CJ-Johnson** [comment]
@miscco Upon closer inspection, I believe the existing specifiers are correct. Check the code comments above them.

As for move-assignment, it isn't important to mark noexcept.

Thanks for the report and happy Abseiling 😄
