### ISSUE TITLE
Conflicted definitions of ABSL_ATTRIBUTE_ALWAYS_INLINE

### ISSUE THREAD

**Issue by Bak-Jin-Hyeong** [abseil/abseil-cpp#343]
In MSVC, 
The `ABSL_ATTRIBUTE_ALWAYS_INLINE` defined in the `absl/base/attributes.h` file is different from that defined in the `absl/random/internal.h`

When `absl/random/internal/randen.cc` is compiled, the definition of `absl/base/attributes.h` is used since the include directive of `absl/base/internal/raw_logging.h`

Is this intended?
I found this at https://github.com/abseil/abseil-cpp/commit/e9324d926a9189e222741fce6e676f0944661a72.

**Comment by derekmauro** [comment]
It looks like an error to me. I think what happened was that someone realized that the definition in `absl/base/attributes.h` is hard to change because MSVC is pickier about the placement of `__forceinline` than GCC/LLVM are about their equivalent attribute. It would have required fixing many users of `ABSL_ATTRIBUTE_ALWAYS_INLINE`. As a workaround we can rename the copy of the macro in the `random` subdirectory until someone actually has time to fix the canonical copy in `absl/base/attributes.h`.

**Comment by shaindelschwartz** [comment]
The latest push should address this.
