### ISSUE TITLE
Performance of flat_hash_set copy constructor

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [abseil/abseil-cpp#346]
Hi!

I have been running some measurements for flat_hash_set and I stumbled on the fact that coping takes some unreasonable time.
```
              vector    flat_hash_set
100    ints   154 ns      1340 ns
1000   ints   151 ns      12682 ns
10000  ints   2439 ns     128694 ns      
100000 ints   27217 ns    1295955 ns
```

Looking through the code, found that you rehash on copy.
https://github.com/abseil/abseil-cpp/blob/74d91756c11bc22f9b0108b94da9326f7f9e376f/absl/container/internal/raw_hash_set.h#L817
Is this intended behaviour?
If it is - can it be commented out explicitly maybe, I didn't find anything in the comments that would indicate this:
https://github.com/abseil/abseil-cpp/blob/74d91756c11bc22f9b0108b94da9326f7f9e376f/absl/container/flat_hash_set.h#L121

**Comment by derekmauro** [comment]
Yes, this behavior is intentional.

Not only do we randomize `absl::Hash` per-process, but each table object adds its own entropy hash function. There are various reasons to do this, for example, it is an anti-[Hyrum's Law](http://www.hyrumslaw.com/) technique, and it helps expose latent bugs caused by assuming iteration order. (I recently gave a similar answer to #339.)

From the above, it follows that (re-)hashing is necessary upon construction. Experience tells us that copying a hash container is a relatively rare operation.

We can take it as an action item to improve our documentation.

**Comment by DenisYaroshevskiy** [comment]
I see - as long as this is intentional.
It's in a conflict (for my money) with principle of providing effective basis (every operation should be doable in the most efficient way from the public interface - and it is possible to copy faster.

Do you think that if there was a standard container, similar to flat_has_set, it would be good for it to rehash on copy too?

**Comment by derekmauro** [comment]
`absl::flat_hash_set` is not a Standard container, nor is it a drop in replacement for one. It has very different design priorities than a Standard container. Standard containers have a don't pay for what you don't use philosophy, so it is hard to imagine they would choose this design. `absl::flat_hash_set` is designed for compatibility over time in a large codebase, while being fast in what our experience tells us is "normal" usage. This design philosophy is probably foreign to most programmers. It is only when you have billions of lines of code to maintain that you start to see why we have different priorities.
