### ISSUE TITLE
StrCat name collision with StrCat in shlwapi.h

### ISSUE THREAD

**Issue by runminlook** [abseil/abseil-cpp#377]
https://docs.microsoft.com/en-us/windows/win32/api/shlwapi/nf-shlwapi-strcatw
The problem is:
shlwapi define StrCat to StrCatW

**Comment by mbxx** [comment]
This has come up a few times across various Google open source projects (e.g., https://github.com/google/benchmark/issues/545).  We're in a bit of a bad spot because the `StrCat` in `shlwapi.h` is a macro, so even properly namespaced uses of `absl::StrCat` conflict, and `absl::StrCat` is so pervasive in Google's codebase and so idiomatic in the minds of Google's engineers that it's not something we're open to renaming.

Can you `#undef StrCat` after you include `shlwapi.h` (https://github.com/google/benchmark/pull/546/files)?  That's the cleanest solution if it works for you.
