### ISSUE TITLE
Cannot use //absl/synchronization

### ISSUE THREAD

**Issue by lshamis** [abseil/abseil-cpp#39]
I'm using `http_archive` to add abseil-cpp to my WORKSPACE.
When trying to use `//absl/synchronization`, I get the following error:

    .../external/com_google_absl/absl/time/BUILD.bazel:27:1: no such package '@com_googlesource_code_cctz//': The repository could not be resolved and referenced by '@com_google_absl//absl/time:time'

Until https://github.com/bazelbuild/bazel/issues/1943 is resolved, recursive WORKSPACE file loading is not supported.

A possible solution to unblock `//absl/synchronization` would be to split `//absl/time` and `time.h`, so that `Duration` and `Time` are in separate BUILD rules from `TimeZone`. Not sure how easy or hard that would be.

**Comment by derekmauro** [comment]
This is working as intended. I haven't followed the Bazel recursive WORKSPACE discussion, but naively I would think it is going to run into the diamond dependency problem. What happens when (sub-)projects depend on different versions of the same library? There is a long discussion of this concept in the CppCon introduction to Abseil: https://youtu.be/tISy7EJQPzI?t=902

Anyway, the solution to this is to add com_googlesource_code_cctz to your WORKSPACE file in the root of your project.
