### ISSUE TITLE
Abseil is conflict with tcmalloc

### ISSUE THREAD

**Issue by tjb1216** [abseil/abseil-cpp#42]
If I link abseil and tcmalloc together in my program,  It will shutdown and say "Check failed: MallocHook::RemoveNewHook(&InitialNewHook):". But if I use abseil only or tcmalloc only, It will run OK， so I think abseil is conflicted with tcmalloc.

**Comment by tjb1216** [comment]
I put absl after tcmalloc, and it works, I don't know if there are any hiddlen problem.

**Comment by ahedberg** [comment]
Didn't have a chance to take a look at this today, but I'll investigate tomorrow. Thanks for your patience!

**Comment by ahedberg** [comment]
@tjb1216 - are you using Bazel to build your project? gperftools doesn't provide a Bazel BUILD file, so if you have one that works, I'd like to borrow it rather than spend time reinventing the wheel.

**Comment by derekmauro** [comment]
@ahedberg - You shouldn't need a BUILD file to reproduce this.  You can compile gperftools separately and then link against it.  Ping me if you need more details.

**Comment by ahedberg** [comment]
Thanks @derekmauro - finally figured out where my built-from-source libtcmalloc.so was hiding.

Current theory (assuming use of LD_PRELOAD to use tcmalloc instead of the system malloc):
* Calls to `MallocHook::InitialNewHook` are using the Abseil implementation.
* The failing call to `MallocHook::RemoveNewHook(&InitialNewHook)` is using the tcmalloc/gperftools implementation.
* This means means that there are two `HookList<MallocHook::NewHook>` objects in any program - one for Abseil (where things get added), and one for tcmalloc.
* So there's nothing to remove from the tcmalloc `HookList` in `RemoveNewHook`, which causes the check failure (because `HookList<MallocHook::NewHook>::Remove` returns false).

We think this might have something to do with both Abseil and tcmalloc overriding mmap, but I need to investigate further.

**Comment by ahedberg** [comment]
@derekmauro and I figured out that the extern "C" parts of MallocHook and MallocExtension are in conflict between tcmalloc and absl, as they have the same names. I'm working on a fix.

**Comment by ahedberg** [comment]
Apologies for the silence here. We're still discussing how best to fix this internally. Rest assured we haven't forgotten about this.

**Comment by ahedberg** [comment]
This has been fixed. Please let us know if you're experiencing additional issues using tcmalloc with Abseil.
