### ISSUE TITLE
What is glibcxx_debug_traits.h?

### ISSUE THREAD

**Issue by nelhage-stripe** [abseil/abseil-cpp#58]
[str_split_internal](https://github.com/abseil/abseil-cpp/blob/1b8dacca622ad547b08bccf523529ef09e2d581f/absl/strings/internal/str_split_internal.h#L33) has an `#include <glibcxx_debug_traits.h>` if `_GLIBCXX_DEBUG` is enabled. 

My system has no `glibcxx_debug_traits.h`, and the only references I can find on Google are includes from this project and `google/sensei`. Is this a Google-internal file of some sort? Should this include be removed? If not, where can I find a `glibcxx_debug_traits.h`?

**Comment by astrelni** [comment]
Thanks for bringing this up. It is something that slipped past, I will work on resolving it.

**Comment by astrelni** [comment]
Status update:

The issue here is that when compiled with _GLIBCXX_DEBUG, STL containers are aliases of special debug container types. Each of these containers inherits from a corresponding non-debug version and enables implicit construction from that version. When doing direct initialization, this extra constructor causes ambiguity. So the following would fail to compile:

```
std::vector<std::string> v(absl::StrSplit("a,b,c", ','));
```

while the following remains ok:

```
std::vector<std::string> v = absl::StrSplit("a,b,c", ',');
```

This is a missed include of a file that takes care of this issue. I am hoping to have a fix in soon.

**Comment by astrelni** [comment]
Fix is in review internally. 

Considering peoples' end of year schedules it may not be part of a release until early January.

**Comment by astrelni** [comment]
This should be fixed now with https://github.com/abseil/abseil-cpp/commit/0271cd3

**Comment by astrelni** [comment]
The fix has had to be rolled back due to an internal brake that was not detected until after this got released. The rollback will likely hit github tomorrow. I will hopefully have a slightly modified version of the fix no later than early next week.

**Comment by astrelni** [comment]
Looks like the rollback and new fix came out in the same release this morning https://github.com/abseil/abseil-cpp/commit/4132ce2
