### ISSUE TITLE
Difference between abseil-cpp and mini_chromium

### ISSUE THREAD

**Issue by hongnod** [abseil/abseil-cpp#59]
Both of abseil-cpp and mini_chromium are from Google, the question is what is the difference and why create another wheel?

**Comment by tituswinters** [comment]
The vast majority of code that has been authored at Google is written in an internal codebase against the APIs that are now released as Abseil.  Many years ago, when Chromium first left that codebase, some of those things were forked.  They have diverged.

Abseil has more developers on it than the equivalent assignment for common libraries in Chromium, far more code depending on it, and far more developers using it.  My expectation is that over time the Chromium libraries will adopt Abseil instead of maintaining their fork - but I cannot promise that outcome.

It's also worth mentioning that Abseil is tasked with releasing a much larger collection of APIs - over time, this will be a significantly larger collection.

Does that explain it sufficiently?

Also, if you haven't watched it, the keynote announcement explains some of the reasoning and policy differences between these projects:
https://www.youtube.com/watch?v=tISy7EJQPzI

**Comment by hongnod** [comment]
thanks for such detail comments.
