### ISSUE TITLE
Excess source files included in release

### ISSUE THREAD

**Issue by mmp** [abseil/abseil-cpp#7]
Two files are included in the release that don't seem to fit. (Neither is referenced from the shipped BUILD.bazel files):

1. synchronization/internal/mutex_nonprod.cc doesn't build (unable to include "base/init_google.h")

2. strings/strip.cpp doesn't build since `StripBrackets()` is used (by `StripCurlyBraces()`) before it's defined and there's no forward declaration for it.

**Comment by derekmauro** [comment]
It seems like you are probably trying to build this without Bazel, which is fine.

1. You're right that synchronization/internal/mutex_nonprod.cc isn't referenced, but I think the error you are seeing is actually from strings/fastmem_test.cc, which was not supposed to be in the release.  I'll be removing fastmem_test.cc this shortly.  mutex_nonprod.cc is a mostly API compatible implementation of Mutex, but for platforms not supported by the production implementation.  Internally there is a select statement in the BUILD.bazel file that picks this implementation over mutex.cc when on one of those platforms, but since the release doesn't support any of those platforms today, it isn't referenced. Just don't compile this file and you should be fine.

2. You're also right about strings/strip.cc. The only interfaces from strings/strip.h that are included are inlined in that header file.  I'll also be removing the strip.cc file shortly.

**Comment by mmp** [comment]
Sounds good. (Indeed, these were discovered when hacking together a cmake file for abseil, which started out by trying to compile all provided source files.)
