### ISSUE TITLE
Behavior of node handles on b-trees

### ISSUE THREAD

**Issue by ddcc** [abseil/abseil-cpp#755]
1. Why does the key() method of node handles have a const return type? Is this an intentional design decision to differ from STL, and if so, it would be good to document this somewhere. Otherwise, a use case for key() with STL data structures is to extract an element, modify only the key (e.g. in a map), and then reinsert it.
2. I'm assuming this is true, but does extraction and/or insertion of node handles invalidate iterators, like insertion and deletion?

**Comment by ezbr** [comment]
1. We support C++11 in absl, and because value_type for maps is std::pair<const Key, T>, I think we can't correctly implement mutable access to the key - for that we need std::launder (C++17 feature). For standard layout value_types, I think we could potentially support mutable key access in node handles in C++11, but it would not be the case for all types - see https://github.com/abseil/abseil-cpp/blob/f66bc749282dd7cffc68b641f527740e95e90cfa/absl/container/internal/container_memory.h#L320. Agreed that we should document this API difference.
2. Yes.

**Comment by ddcc** [comment]
Would it be possible to support this via an ifdef when compiling with C++17? Node handles are a C++17 feature anyway. I don't know if there's a policy on this wrt maintenance.

I have a local commit that [makes it work for node handles](https://github.com/ddcc/abseil-cpp/commit/66b31a3087b71edf5b3bc835cd91034dcab7ef29), but looks like it also breaks key non-mutability for other accesses through a reference.

**Comment by ezbr** [comment]
Yes, I will work on enabling mutable keys in node handles when compiling with C++17.

[That change](https://github.com/ddcc/abseil-cpp/commit/66b31a3087b71edf5b3bc835cd91034dcab7ef29) has undefined behavior when the members aren't standard layout types. From https://en.cppreference.com/w/cpp/language/union:
"It's undefined behavior to read from the member of the union that wasn't most recently written... If two union members are standard-layout types, it's well-defined to examine their common subsequence on any compiler."

**Comment by ddcc** [comment]
Thanks! Yeha, it's just hack to get my application working.

**Comment by ezbr** [comment]
As of https://github.com/abseil/abseil-cpp/commit/c6b3f2cf583d8fec124f9d70a172b513363506fe, we now have mutable access to keys in node handles when compiled with C++17 or later.

**Comment by ddcc** [comment]
Thanks for landing this support!
