### ISSUE TITLE
absl::CondVar: FIFO or LIFO wake ordering?

### ISSUE THREAD

**Issue by adembo** [abseil/abseil-cpp#79]
It isn't clear from the documentation in mutex.h whether `absl::CondVar::Signal` wakes up waiters in FIFO or LIFO order. [This comment](https://github.com/abseil/abseil-cpp/blob/master/absl/synchronization/mutex.h#L716) says FIFO, while [this one](https://github.com/abseil/abseil-cpp/blob/master/absl/synchronization/mutex.h#L749) suggests LIFO.

The underlying implementation looks like it uses a stack, so maybe the first comment just needs to be corrected?

**Comment by derekmauro** [comment]
Thank you for bringing this to our attention. I'll get the documentation fixed.

I was a bit surprised that the documentation makes any claims at all about about this. The practical answer is that you should never assume anything about the order in which threads will run. Since you have no way of knowing exactly when a thread was blocked, the order in which threads are woken must not matter to the programmer.

For this reason I'm leaning towards removing these claims from the documentation, but I'm going to poll a few other people and see that they think.

**Comment by danburkert** [comment]
I work with @adembo, so I have some context about the motivation behind the question.

We're looking at using the abseil condvar in order to get LIFO wakeup ordering amongst sleeping threads in a threadpool.  This ends up being important in our use-case because it makes it easier to clean up more threads faster with a simple timeout on the condvar, and because it means less costly context switches (fewer threads doing more of the work).  In our case we don't need a guaranteed LIFO ordering; a 'best-effort' solution would be good enough.

**Comment by derekmauro** [comment]
I've already submitted the change that removes the claims about the order in which threads are woken (as I mentioned, I was very surprised to see that claim in the first place) and it should be propagated to GitHub shortly.

I'd also urge you not to depend on this implementation detail. See also: [Hyrum's Law](http://www.hyrumslaw.com/).

For the threadpool use case, LIFO wakeup ordering isn't crazy thing want, for the reasons you mentioned. But it shouldn't be hard or expensive to do that bookkeeping yourself and isolate your code from implementation details. The idea being that when a thread is blocked waiting for work, you can add your thread to a doubly-linked list of blocked threads, each waiting on a separate `absl::CondVar`, so that it's easy to determine exactly which thread you want wake when work is available.

**Comment by derekmauro** [comment]
Documentation change is in 5a8de8a37e3e282d22f69ca67b4aba8e4cca63ae. Let us know if you have questions.
