### ISSUE TITLE
absl/base/internal/unaligned_access.h

### ISSUE THREAD

**Issue by cadenzasong** [abseil/abseil-cpp#792]
Hi there,

In absl/base/internal/unaligned_access.h:
aren't the __sanitizer_unaligned* functions msan specific?

If so, should the beginning:
```
#if defined(ABSL_HAVE_ADDRESS_SANITIZER) || \
    defined(ABSL_HAVE_THREAD_SANITIZER) || defined(ABSL_HAVE_MEMORY_SANITIZER)
```
become only:
```
#if defined(ABSL_HAVE_MEMORY_SANITIZER)
```

Thanks.

**Comment by derekmauro** [comment]
That doesn't appear to be the case: https://github.com/llvm/llvm-project/blob/14948a08f31b6e3b555f73339504efd867835d27/compiler-rt/include/sanitizer/common_interface_defs.h#L57-L61

Is there some problem you are trying to solve?

**Comment by cadenzasong** [comment]
> That doesn't appear to be the case: https://github.com/llvm/llvm-project/blob/14948a08f31b6e3b555f73339504efd867835d27/compiler-rt/include/sanitizer/common_interface_defs.h#L57-L61
> 
> Is there some problem you are trying to solve?

Thanks for the pointer.

I was trying to do an asan-only build (sorry if this is too vague, not sure what's the disclosure policy from the company, but I'm sure people here do plenty of asan builds in general) and hit a linker issue with undefined symbol for "__sanitizer_unaligned_load32" etc.

**Comment by derekmauro** [comment]
Just a guess: Did you remember to pass `-fsanitize=address` to the linker? It looks like we all pass `-fsanitize-link-c++-runtime`, but I can't remember if we need that for ASAN or UBSAN. Actually, `-fsanitize-link-c++-runtime` might be necessary if you build C++ code with `clang` instead of `clang++`.

Have a look at the script we use for these builds, maybe you can find a hint: https://github.com/abseil/abseil-cpp/blob/master/ci/linux_clang-latest_libcxx_asan_bazel.sh

**Comment by derekmauro** [comment]
I don't think there is anything actionable on our end here.
