### ISSUE TITLE
absl::inline_string in the pipe ?

### ISSUE THREAD

**Issue by stayprivates** [abseil/abseil-cpp#81]
Hi, 

Is there an absl::inline_string object, much like absl::inline_vector in development?  I'm asking because if it is, in the not so distance future or currently in progress, I'll wait, don't want to waiste time doing stuff that already exists.. If not, I would give a try at creating one.

The end goal would also be to add support for all string related functions, StrCat and alike.

Regards,

Mario

**Comment by mbxx** [comment]
No, that's not something we're working on because the implementations of std::string provided by GCC, LLVM, and MSVC all include the small string optimization.  (Please forgive me if you're already aware of this, but that's where small strings are stored inline and larger strings are allocated on the heap.)  The only limitation I'm aware of is unlike absl::InlinedVector, you can't specify how many characters are inlined from within your program.  Does that give you what you need?  Or am I misunderstanding what you're looking for?

Since you mentioned extending StrCat, I should also mention that we're still debating whether or not we want to support extending StrCat to handle user-defined types.  We've had some requests for it, so it's on our radar, but we haven't come to a consensus as to whether or not it's something we want to commit to supporting.

**Comment by stayprivates** [comment]
Stuck using 4.8.3, it does not have small string optimisation.  Further more most of our string are too big for sso.

Been playing with llvm SmallString, getting good performance boost but I'd rather we use abseil than go tho the trouble of incorporating llvm stuff in our code base. Abseil is way friendlier as a lib.

**Comment by mbxx** [comment]
Ah, got it, that makes a lot of sense.

Thanks for thinking of us and I'm really glad to hear that you find Abseil friendly to work with.  Unfortunately we don't have an inlined string type coming out, so I don't think we can help.
