### ISSUE TITLE
inline_variable Note. identity_t for correct const name order.

### ISSUE THREAD

**Issue by kohei306** [abseil/abseil-cpp#821]
Regarding the below note in https://github.com/abseil/abseil-cpp/blob/master/absl/base/internal/inline_variable.h.
// Note:
//   identity_t is used here so that the const and name are in the
//   appropriate place for pointer types, reference types, function pointer
//   types, etc..

Is this behavior (using identity_t solves the correct order of const and name) guaranteed in standard? If so where is the corresponding statement in standard?

**Comment by vslashg** [comment]
One section of the spec that goes into the details here is [dcl.type], and especially [dcl.type.cv], but I don't think diving into the spec is helpful or necessary here.

What this code is doing is using a simple wrapper so that the declaration has the correct type, despite the limits of C macros and the peculiarities of declaration syntax in C++.

If the macro were simply
```
#define ABSL_INTERNAL_EXTERN_DECL(type, name) \
  extern const type name;
```
then the macro
`ABSL_INTERNAL_EXTERN_DECL(char*, ptr)`
would expand to
`extern const char* ptr;`,
which would declare `ptr` as a non-const pointer to `const char`.  This would be the wrong type.

The actual macro instead expands to
`extern const ::absl::internal::identity_t<char*> ptr;`
which delcares `ptr` as a `const` pointer to non-const `char`, which is what is actually needed.

Because this in an internal header, this is not a stable interface and not one we intend users to access directly, so that's why we don't go into great detail in these comments.  It just needs to be enough of a breadcrumb for future maintainers to understand our intent.  I'm not sure it requires further clarification.

**Comment by kohei306** [comment]
Thanks for the detail explanation.
