### ISSUE TITLE
VS2017 build warning C4819 on non-english code page.

### ISSUE THREAD

**Issue by gavxin** [abseil/abseil-cpp#85]
Hello, I'm trying to build abseil-cpp on Windows with installed VS 2017. My default code page is 936 (Simplified Chinese) and when build abseil will occur following error.

```
error C2220: warning treated as error - no 'object' file generated
warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
```

Here is one solution. Add `/utf-8` option to `MSVC_FLAGS` in file `absl/copts.bzl`

```
index 20c9b61..0052db8 100644
--- a/absl/copts.bzl
+++ b/absl/copts.bzl
@@ -126,6 +126,7 @@ MSVC_FLAGS = [
     "/DNOMINMAX",  # Don't define min and max macros (windows.h)
     "/DWIN32_LEAN_AND_MEAN",  # Don't bloat namespace with incompatible winsock versions.
     "/D_CRT_SECURE_NO_WARNINGS",  # Don't warn about usage of insecure C functions
+    "/utf-8",   # Fix C4819 for non-english code page.
 ]
```

**Comment by JonathanDCohen** [comment]
Which character was the compiler complaining about?

**Comment by gavxin** [comment]
I found two position.

`unaligned_access.h` the two double quotes are unicode chars. 

https://github.com/abseil/abseil-cpp/blob/46ed9d96d1412223d22430ca2aed4411894c2d63/absl/base/internal/unaligned_access.h#L145

`absl/strings/str_split_test.cc` the test case `TEST(Split, UTF8)` is testing utf-8 string splitting. It's just test case so maybe no need to change.

https://github.com/abseil/abseil-cpp/blob/46ed9d96d1412223d22430ca2aed4411894c2d63/absl/strings/str_split_test.cc#L622-L642

After modify these two file, the build success.

**Comment by JonathanDCohen** [comment]
Since Abseil is fairly low-level, instead of forcing utf-8 in msvc builds, I think the correct move is to make our source files all ascii.  So I'll write up a patch to change that test to use unicode escape characters, which should make it agnostic to file encoding.

That being said, Abseil files are utf8 internally, so I'm not sure what other monsters there may be lurking if someone tries to use abseil source with other encodings.

**Comment by gavxin** [comment]
It make sense, it's better make source file as ascii than forcing utf-8 for msvc.

Thanks

**Comment by manshreck** [comment]
Note that the test is actually testing utf8 characters. I don't see how we can have a test for utf8 in ASCII ...

We should definitely prefer ASCII for source files, IMO, but I'm not sure requiring them to be ASCII is the best option.

**Comment by mbxx** [comment]
Jon and I chatted about this yesterday, and I came to the conclusion that Abseil files should be ASCII.  Abseil strives to be as broadly usable as possible.  Usually this takes the form of writing code that works on a wide variety of platforms, dodging bugs in those platforms if necessary.  Here it means avoiding UTF-8 because some toolchains we want to support can't handle it.

The alternative isn't as bad as I feared: escaping the unicode characters in the test strings lets them be UTF-8 test strings that are specified using only ASCII characters in the source code.  I'm a little sad, because suddenly it's no longer clear at a glance that the escaped characters are well-formed UTF-8, but this feels like the right thing to do to me.

**Comment by jorgbrown** [comment]
The MSVC error message says "Save the file in Unicode format to prevent data loss"

Just curious: What does it mean to save the file in Unicode format?  Does it just add a UTF-8 BOM to the beginning of the file?  Or is there additional metadata in the filesystem to tell MSVC that the file is Unicode?

**Comment by JonathanDCohen** [comment]
"Unicode format" seems ambiguous.  Anyways it looks like my internal patch to remove non-ascii characters has been upstreamed, and ASCII fits in all flavors of Unicode.  Is this problem still persisting?

**Comment by gavxin** [comment]
Try to build 0ec11bad6fc18822e851b25344f027491cc85746 , `str_split_test.cc` still cause following warnings.

```
ERROR: E:/xx/abseil-cpp/absl/strings/BUILD.bazel:214:1: C++ compilation of rule '//absl/strings:str_split_test' failed (Exit 2)
absl/strings/str_split_test.cc(624): error C2220: warning treated as error - no 'object' file generated
absl/strings/str_split_test.cc(624): warning C4566: character represented by universal-character-name '\u1F79' cannot be represented in the current code page (936)
absl/strings/str_split_test.cc(644): warning C4566: character represented by universal-character-name '\u00E4' cannot be represented in the current code page (936)
absl/strings/str_split_test.cc(645): warning C4566: character represented by universal-character-name '\u00E4' cannot be represented in the current code page (936)
```

It just test, maybe I should ignore it.

**Comment by ahedberg** [comment]
I'm looking into fixing the `str_split_test.cc` failures.

**Comment by ahedberg** [comment]
This has been fixed internally; just waiting for the change to be propagated to GitHub.

**Comment by mbxx** [comment]
I just pushed the change to GitHub.
