### ISSUE TITLE
Specialize numeric_limits for absl::Duration?

### ISSUE THREAD

**Issue by versatran01** [abseil/abseil-cpp#850]
I was using `absl::Duration` with `boost::accumlator` to compute statistics on time,
which requires specialization of `std::numeric_limits<absl::Duration>`.
Would this be a good thing to have within the header?

**Comment by tituswinters** [comment]
At a high level: `Duration` isn't numeric, so no.
In practice, this also touches on a couple messy things in `numeric_limits` - WG21 knows (now) that type traits should be individual, not bucketed like `numeric_limits`. Some of the individual sub-traits in numeric_limits could apply to Duration (it could say yes to "is_exact", for instance), but many of them aren't a clear yes or no ("is_signed" doesn't apply, for instance - it isn't either signed nor unsigned, because it isn't numeric). 

It's also largely unclear whether the standard allows specializations of numeric_limits in general: the *implementations* are allowed to do this (and now required to do so, as of C++20, for all builtin integer types). It's hazy at best (and likely forbidden) whether arbitrary user-defined types are allowed to be specialized.
